# Taxonomies, regex patterns, and constant used for profile extraction

# predefined skills for tech related jobs( not mendatory, but can be used for better accuracy) 
DEFAULT_SKILL_TAXONOMY: set[str] = {
    # programming Languages
    "python",
    "java",
    "c++",
    "c#",
    "c",
    "r",
    "go",
    "golang",
    "rust",
    "swift",
    "kotlin",
    "javascript",
    "typescript",
    "php",
    "ruby",
    "sql",
    "html",
    "scala",
    "elixir",
    "haskell",
    "matlab",
    "sas",
    "d3.js",
    "bigquery",
    "hadoop",
    "spark",
    "tableau",
    "power bi",
    "data visualization",
    "deep reinforcement learning",
    "computer graphics",
    "css",
    # Data Science, AI & ML
    "pandas",
    "numpy",
    "scipy",
    "scikit-learn",
    "pytorch",
    "tensorflow",
    "keras",
    "matplotlib",
    "seaborn",
    "machine learning",
    "deep learning",
    "data science",
    "natural language processing",
    "nlp",
    "computer vision",
    "bayesflow",
    "data engineering",
    "data architecture",
    "data governance",
    "data modeling",
    "data quality",
    "data strategy",
    "data analytics",
    "data storytelling",
    "data lakes",
    "data warehouses",
    "data pipelines",
    "data integration",
    "data privacy",
    "data security",
    "data ethics",
    "data visualization best practices",
    "data science methodologies",
    "data science frameworks",
    "data science tools",
    "data science platforms",
    "data science libraries",
    "feature engineering",
    "model deployment",
    "data wrangling",
    "data mining",
    "data visualization tools",
    "big data",
    "cloud computing",
    "artificial intelligence",
    "reinforcement learning",
    "lenstronomy",
    # Web Frameworks & Backend
    "react",
    "angular",
    "vue",
    "django",
    "flask",
    "fastapi",
    "spring",
    "express",
    "node.js",
    "svelte",
    "tailwind",
    "next.js",
    "typescript",
    "nuxt.js",
    "laravel",
    "symfony",
    "codeigniter",
    "spring boot",
    "ruby on rails",
    "asp.net",
    "rest api",
    "graphql",
    "microservices",
    "django rest framework",
    "django",
    "node",
    "express",
    "flask",
    "spring",
    "ruby on rails",
    # Cloud, DevOps & Tools
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "git",
    "github",
    "gitlab",
    "ci/cd",
    "jenkins",
    "terraform",
    "ansible",
    "linux",
    "bash",
    "prometheus",
    "grafana",
    "datadog",
    "splunk",
    "vagrant",
    "chef",
    "puppet",
    "argocd",
    "helm",
    "openshift",
    "rancher",
    # Databases & Storage
    "postgresql",
    "mysql",
    "mongodb",
    "sqlite",
    "redis",
    "elasticsearch",
    "neo4j",
    # Methodologies & General
    "agile",
    "scrum",
    "unit testing",
    "pytest",
    "data analysis",
    "system design",
    "object-oriented programming",
}

# academic Degree with regex
DEGREE_PATTERNS: dict[str, str] = {
    "Bachelor": r"\b(B\.?S\.?|B\.?A\.?|Bachelor|BSc|B\.?Tech)\b",
    "Master": r"\b(M\.?S\.?|M\.?A\.?|Master|MSc|M\.?Tech)\b",
    "PhD": r"\b(Ph\.?D\.?|Doctorate|Doctor of Philosophy)\b",
}

# contact Information regex 
CONTACT_PATTERNS: dict[str, str] = {
    "email": r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b",
    "phone": r"\(?\+?\d{1,3}\)?[-.\s]?\d{1,4}[-.\s]?\d{1,4}[-.\s]?\d{1,9}",
    "github": r"(?:https?://)?(?:www\.)?github\.com/[A-Za-z0-9_-]+",
    "linkedin": r"(?:https?://)?(?:www\.)?linkedin\.com/in/[A-Za-z0-9_-]+",
}

# section Header extraction 
SKILLS_SECTION_PATTERN = (
    r"(?:TECHNICAL\s+SKILLS|SKILLS|COMPETENCIES|TOOLS)\s*:?\n?" # As of now
    r"(.*?)(?=\n\n|\n[A-Z\s]{4,}:|\Z)"
)

# technical entity pattern 
TECH_ENTITY_PATTERN = (
    r"\b([A-Z][a-z0-9]+[A-Z][a-zA-Z0-9]+)\b|"  # camelCase (OpenCV, HuggingFace)
    r"\b([A-Z]{3,5})\b|"  # acronyms (CUDA, FPGA, LLM, NLP)
    r"\b([a-zA-Z0-9\-_]+\.(?:js|py|io|ai|db))\b"  # code extensions (Next.js, Node.js)
)

# non-skill words to ignore during dynamic discovery
STOPWORD_EXCLUSIONS: set[str] = {
    "email",
    "phone",
    "github",
    "linkedin",
    "education",
    "experience",
    "summary",
    "projects",
    "profile",
}